import { NextRequest, NextResponse } from 'next/server';

export const runtime = 'nodejs';

interface Image2Request {
  topic?: string;
  content?: string;
  coverStyle?: string;
  visualGoal?: string;
  referenceImage?: string;
}

interface Image2Payload {
  model?: string;
  prompt: string;
  image?: string;
  reference_image?: string;
  size: string;
  response_format: string;
}

const STYLE_GUIDE: Record<string, string> = {
  '爆款封面': '小红书爆款封面：大标题强对比、红粉强调色、信息密度中高、第一眼能看懂主题。',
  '干货卡片': '干货教程卡片：清单式排版、重点数字突出、留白清晰、适合图文轮播第一页。',
  '治愈手账': '治愈手账风：暖白背景、便签/胶带/手写感元素、柔和粉红点缀、不要科技感。',
  '专业测评': '专业测评风：对比表格、结论标签、可信赖的产品评测感、干净克制。',
};

function buildPrompt(body: Required<Pick<Image2Request, 'topic' | 'coverStyle'>> & Pick<Image2Request, 'content' | 'visualGoal' | 'referenceImage'>) {
  const referenceInstruction = body.referenceImage
    ? '\n- 用户提供了参考图：请参考其构图、颜色关系、文字层级和整体情绪，但不要照搬具体文字或侵权元素。'
    : '';

  return `为小红书/Rednote 图文矩阵生成一张 3:4 竖版封面图。

主题：${body.topic}
封面风格：${STYLE_GUIDE[body.coverStyle] || STYLE_GUIDE['爆款封面']}
内容要点：${body.content || '根据主题自动提炼 2-4 个视觉卖点'}
视觉目标：${body.visualGoal || '让用户一眼知道这篇笔记能解决什么问题，并愿意点开'}${referenceInstruction}

硬性要求：
- 画面比例 3:4，适合小红书首图封面。
- 中文大标题醒目，最多 12 个字；副标题最多 18 个字。
- 主色使用小红书红 #FF2442 与暖粉 #FF6B81，背景偏暖白 #FAFAFA。
- 圆角卡片、便签、色卡、轻微纸张阴影；不要科技蓝紫渐变，不要 3D 渲染。
- 画面要像可直接发布的封面，不要出现明显 AI 水印、乱码文字或多余英文。
- 如果参考图存在，优先学习它的版式骨架和视觉节奏，再融入当前主题。`;
}

function escapeXml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function createFallbackSvg(topic: string, coverStyle: string, content?: string) {
  const safeTopic = escapeXml(topic.slice(0, 18));
  const safeStyle = escapeXml(coverStyle);
  const safeContent = escapeXml((content || '参考图 + 内容要点 → 可发布封面').slice(0, 28));
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="1200" viewBox="0 0 900 1200">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#fff7f8"/>
      <stop offset="1" stop-color="#fff"/>
    </linearGradient>
    <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">
      <feDropShadow dx="0" dy="20" stdDeviation="24" flood-color="#ff2442" flood-opacity="0.16"/>
    </filter>
  </defs>
  <rect width="900" height="1200" fill="url(#bg)"/>
  <circle cx="760" cy="130" r="120" fill="#ff2442" opacity="0.08"/>
  <circle cx="110" cy="1020" r="170" fill="#ff6b81" opacity="0.10"/>
  <g filter="url(#shadow)">
    <rect x="82" y="132" width="736" height="936" rx="54" fill="#fff"/>
  </g>
  <rect x="128" y="184" width="190" height="54" rx="27" fill="#fff0f2"/>
  <text x="158" y="219" font-family="Noto Sans SC, PingFang SC, Arial" font-size="25" font-weight="700" fill="#ff2442">${safeStyle}</text>
  <text x="132" y="396" font-family="Noto Sans SC, PingFang SC, Arial" font-size="76" font-weight="800" fill="#1a1a1a">
    <tspan x="132" dy="0">${safeTopic}</tspan>
  </text>
  <rect x="132" y="470" width="636" height="6" rx="3" fill="#ff2442"/>
  <text x="132" y="548" font-family="Noto Sans SC, PingFang SC, Arial" font-size="34" font-weight="500" fill="#555">
    <tspan x="132" dy="0">${safeContent}</tspan>
  </text>
  <g transform="translate(132 660)">
    <rect width="220" height="150" rx="28" fill="#fff5d8" transform="rotate(-4)"/>
    <rect x="260" y="8" width="240" height="150" rx="28" fill="#ffe4e9" transform="rotate(3 380 83)"/>
    <rect x="120" y="192" width="390" height="120" rx="28" fill="#f7f7f7"/>
    <text x="42" y="86" font-family="Noto Sans SC, PingFang SC, Arial" font-size="28" font-weight="700" fill="#1a1a1a">标题钩子</text>
    <text x="310" y="96" font-family="Noto Sans SC, PingFang SC, Arial" font-size="28" font-weight="700" fill="#ff2442">视觉卖点</text>
    <text x="180" y="264" font-family="Noto Sans SC, PingFang SC, Arial" font-size="28" font-weight="700" fill="#1a1a1a">矩阵可复用模板</text>
  </g>
  <text x="132" y="1005" font-family="Inter, Arial" font-size="24" fill="#8c8c8c">Generated by Rednote Content Factory · image2 bridge preview</text>
</svg>`;

  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

function extractImageUrl(data: unknown): string | null {
  if (!data || typeof data !== 'object') return null;
  const record = data as Record<string, unknown>;

  const directKeys = ['image_url', 'imageUrl', 'url', 'output_url'];
  for (const key of directKeys) {
    if (typeof record[key] === 'string') return record[key] as string;
  }

  const arrays = ['data', 'images', 'output', 'result'];
  for (const key of arrays) {
    const value = record[key];
    if (Array.isArray(value)) {
      for (const item of value) {
        if (item && typeof item === 'object') {
          const itemRecord = item as Record<string, unknown>;
          if (typeof itemRecord.url === 'string') return itemRecord.url;
          if (typeof itemRecord.image_url === 'string') return itemRecord.image_url;
          if (typeof itemRecord.b64_json === 'string') return `data:image/png;base64,${itemRecord.b64_json}`;
        }
        if (typeof item === 'string') return item;
      }
    }
  }

  if (typeof record.b64_json === 'string') return `data:image/png;base64,${record.b64_json}`;
  return null;
}

async function callImage2(prompt: string, referenceImage?: string) {
  const endpoint = process.env.IMAGE2_API_URL;
  if (!endpoint) return null;

  const payload: Image2Payload = {
    model: process.env.IMAGE2_MODEL || 'image2',
    prompt,
    size: process.env.IMAGE2_SIZE || '900x1200',
    response_format: 'url',
  };

  if (referenceImage) {
    payload.image = referenceImage;
    payload.reference_image = referenceImage;
  }

  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (process.env.IMAGE2_API_KEY) headers.Authorization = `Bearer ${process.env.IMAGE2_API_KEY}`;

  const response = await fetch(endpoint, {
    method: 'POST',
    headers,
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const detail = await response.text();
    throw new Error(`image2 调用失败：${response.status} ${detail.slice(0, 200)}`);
  }

  const data = await response.json();
  const imageUrl = extractImageUrl(data);
  if (!imageUrl) throw new Error('image2 返回中没有识别到图片 URL 或 base64');
  return imageUrl;
}

export async function POST(request: NextRequest) {
  try {
    const body = (await request.json()) as Image2Request;
    const topic = body.topic?.trim();

    if (!topic) {
      return NextResponse.json({ error: '请提供封面主题' }, { status: 400 });
    }

    const coverStyle = body.coverStyle || '爆款封面';
    const prompt = buildPrompt({
      topic,
      coverStyle,
      content: body.content,
      visualGoal: body.visualGoal,
      referenceImage: body.referenceImage,
    });

    const generatedUrl = await callImage2(prompt, body.referenceImage);
    const imageUrl = generatedUrl || createFallbackSvg(topic, coverStyle, body.content);

    return NextResponse.json({
      imageUrl,
      prompt,
      mode: generatedUrl ? 'image2' : 'local-preview',
      note: generatedUrl
        ? '已通过 IMAGE2_API_URL 桥接真实生图服务。'
        : '未配置 IMAGE2_API_URL，当前返回本地 SVG 预览；配置 IMAGE2_API_URL/IMAGE2_API_KEY 后会调用真实 image2。',
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : '封面生成失败';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
